welcome:
  _name: Announcements
  _page: index
  mailinglist:
    _name: Mailing List
    _page: mailinglist
  newsletter:
    _name: Newsletter
    _page: newsletter_index
  narchives:
    _name: News Archives
    _page: news_index
meetings:
  _name: Meetings
  _page: meetings_index
  meetings_psa2010:
    _name: PSA 2010
    _page: meetings_psa2010_index
    _show: false
  meetings_psa2008:
    _name: PSA 2008
    _page: meetings_psa2008_index
    _show: false
  meetings_psa2006:
    _name: PSA 2006
    _page: meetings_psa2006_index
    _show: false
philsci_journal:
  _name: "Journal: Philosophy of Science"
  _page: http://journal.philsci.org/
philsci_archive:
  _name: PhilSci Archive
  _page: http://philsci-archive.pitt.edu/
membership:
  _name: Membership
  _page: membership
womens:
  _name: Women's Caucus
  _page: http://www.philsci.org/psawomenscaucus/
  _skip_before: false
resources:
  _name: Resources
  _page: resources_index
  res_education:
    _name: Education
    _page: resources_education_index
  jobs:
    _name: Employment
    _page: resources_jobs_index
    jobs_archive:
      _name: Archive
      _page: resources_jobs_archive
      _show: false
  res_funding:
    _name: Funding Sources
    _page: resources_funding
  res_research:
    _name: Journals, Archives, and On-line Resources
    _page: resources_journals-archives-online
  res_proforgs:
    _name: Professional Organizations
    _page: resources_professionalorgs
  res_engagement:
    _name: Public Engagement
    _page: resources_engagement
about:
  _name: About PSA
  _page: about_index
  governance:
    _name: Governance
    _page: about_governance
  history:
    _name: History of the Association
    _page: about_history
  affiliates:
    _name: Professional Affiliates
    _page: about_affiliates
  bylaws:
    _name: PSA Bylaws
    _page: about_bylaws
remembrances:
  _name: Remembrances
  _page: remembrances_index
  _skip_before: true
