welcome:
  _name: Announcements
  _page: index
  mailinglist:
    _name: Mailing List
    _page: mailinglist
  newsletter:
    _name: Newsletter
    _page: newsletter_index
  narchives:
    _name: News Archives
    _page: news_index
governance:
  _name: PSA Governance
  _page: governance
  bylaws:
    _name: PSA Bylaws
    _page: bylaws
membership:
  _name: PSA Membership
  _page: membership
meetings:
  _name: PSA Meetings
  _page: meetings_index
  meetings_psa2010:
    _name: PSA 2010
    _page: meetings_psa2010_index
    _show: false
  meetings_psa2008:
    _name: PSA 2008
    _page: meetings_psa2008_index
    _show: false
  meetings_psa2006:
    _name: PSA 2006
    _page: meetings_psa2006_index
    _show: false
resources:
  _name: Resources
  _page: resources_index
  philsci:
    _name: for Philosophy of Science
    _page: resources_philsci_index
  students:
    _name: for Students
    _page: resources_student_index
womens:
  _name: PSA Women's Caucus
  _page: http://www.philsci.org/psawomenscaucus/
  _skip_before: true
philsci_journal:
  _name: Journal
  _page: http://journal.philsci.org/